import { CustomId, type Document, type DocumentValue } from "sinterdb-protocol";

import { FindCursor } from "./cursor.js";
import type { SinterDatabase } from "./database.js";
import {
  SinterInsertManyError,
  SinterProtocolError,
  SinterServerError,
} from "./errors.js";
import type { Filter, Sort } from "./filter.js";
import {
  parseCreateIndexResult,
  parseIndexList,
  parseIndexValidation,
  type CreateIndexResult,
  type IndexDefinition,
  type IndexInfo,
  type IndexValidationResult,
} from "./indexes.js";
import { validateCollectionName } from "./namespace.js";
import type {
  DeleteResult,
  UpdateFilter,
  UpdateOptions,
  UpdateResult,
} from "./update.js";

/**
 * A document as accepted for insertion: `_id` is optional, and the server
 * generates one when it is missing.
 */
export type OptionalId<TDocument extends object> = Omit<TDocument, "_id"> & {
  /** The document's `_id`; generated by the server when omitted. */
  readonly _id?: CustomId;
};

/** A document as stored and returned: `_id` is always present. */
export type WithId<TDocument extends object> = Omit<TDocument, "_id"> & {
  /** The document's `_id`. */
  readonly _id: CustomId;
};

/** A shorthand filter that matches fields by equality only. */
export type EqualityFilter<TDocument extends object> = {
  readonly [Key in keyof TDocument]?: TDocument[Key];
};

/** Options for {@link SinterCollection.find}. */
export interface FindOptions<TDocument extends object = Document> {
  /**
   * How many documents the cursor fetches from the server per round trip.
   */
  readonly batchSize?: number;
  /**
   * Sort order as `[path, direction]` pairs, where direction is `1` for
   * ascending and `-1` for descending. Earlier pairs take priority.
   */
  readonly sort?: Sort<TDocument>;
  /** How many matching documents to skip, after sorting. */
  readonly skip?: number;
  /** The maximum number of documents to return. */
  readonly limit?: number;
}

/** The result of {@link SinterCollection.insertOne}. */
export interface InsertOneResult {
  /** Always `true`; a failed insert throws instead. */
  readonly acknowledged: true;
  /** The `_id` of the inserted document, whether supplied or generated. */
  readonly insertedId: CustomId;
}

/** The result of {@link SinterCollection.insertMany}. */
export interface InsertManyResult {
  /** Always `true`; a failed insert throws instead. */
  readonly acknowledged: true;
  /** How many documents were inserted. */
  readonly insertedCount: number;
  /** The `_id` of every inserted document, in input order. */
  readonly insertedIds: readonly CustomId[];
}

/**
 * A collection of documents, typed by `TDocument`.
 *
 * Get one from {@link SinterDatabase.collection}. The type parameter makes
 * filters, updates and results type-checked against your document shape; it
 * is not enforced by the server.
 */
export class SinterCollection<TDocument extends object = Document> {
  /** Carries the document type for the compiler. It has no runtime value. */
  declare protected readonly documentType: TDocument;

  /** The collection name. */
  public readonly name: string;

  public constructor(
    /** The database this collection belongs to. */
    public readonly database: SinterDatabase,
    name: string,
  ) {
    validateCollectionName(name);
    this.name = name;
  }

  /**
   * The database and collection names joined with a dot, such as `app.users`.
   */
  public get namespace(): string {
    return `${this.database.name}.${this.name}`;
  }

  /**
   * Inserts one document.
   *
   * The collection is created if it does not exist. A missing `_id` is
   * generated.
   *
   * @returns The `_id` of the inserted document.
   * @throws {@link SinterServerError} with a `DuplicateKey` name when `_id`
   *   or a unique index value already exists.
   */
  public async insertOne(
    document: OptionalId<TDocument>,
  ): Promise<InsertOneResult> {
    const value = await this.database.client.executeCommand(
      this.database.name,
      "insertOne",
      {
        collection: this.name,
        document: document as unknown as Document,
      },
    );

    return parseInsertOneResult(value);
  }

  /**
   * Inserts several documents in order.
   *
   * An empty array is rejected. If one document fails, the documents before
   * it stay inserted, and the thrown {@link SinterInsertManyError} reports
   * `failedIndex` and the `insertedIds` that were committed.
   *
   * @returns The number of documents inserted and their `_id` values.
   */
  public async insertMany(
    documents: readonly OptionalId<TDocument>[],
  ): Promise<InsertManyResult> {
    let value: DocumentValue;

    try {
      value = await this.database.client.executeCommand(
        this.database.name,
        "insertMany",
        {
          collection: this.name,
          documents: documents.map(
            (document) => document as unknown as Document,
          ),
        },
      );
    } catch (error: unknown) {
      translateInsertManyFailure(error);
    }

    return parseInsertManyResult(value);
  }

  /**
   * Finds the first document that matches the filter, or `null`. Without a
   * filter, it returns the first document in the collection.
   */
  public async findOne(
    filter: Filter<TDocument> = {} as Filter<TDocument>,
  ): Promise<WithId<TDocument> | null> {
    const value = await this.database.client.executeCommand(
      this.database.name,
      "findOne",
      {
        collection: this.name,
        filter: filter as unknown as Document,
      },
    );

    return parseFindOneResult<TDocument>(value);
  }

  /** Deletes the first document that matches the filter. */
  public async deleteOne(filter: Filter<TDocument>): Promise<DeleteResult> {
    return this.runDelete("deleteOne", filter);
  }

  /** Deletes every document that matches the filter. */
  public async deleteMany(filter: Filter<TDocument>): Promise<DeleteResult> {
    return this.runDelete("deleteMany", filter);
  }

  /**
   * Replaces the first matching document with `replacement`.
   *
   * The document keeps its `_id`. Giving the replacement a different `_id`
   * fails with an `ImmutableId` server error. With `upsert`, a replacement is
   * inserted when nothing matches.
   */
  public async replaceOne(
    filter: Filter<TDocument>,
    replacement: OptionalId<TDocument>,
    options: UpdateOptions = {},
  ): Promise<UpdateResult> {
    const value = await this.database.client.executeCommand(
      this.database.name,
      "replaceOne",
      {
        collection: this.name,
        filter: filter as unknown as Document,
        replacement: replacement as unknown as Document,
        ...(options.upsert === undefined ? {} : { upsert: options.upsert }),
      },
    );

    return parseUpdateResult(value, "replaceOne");
  }

  /**
   * Applies an update to the first matching document.
   *
   * With `upsert`, a document seeded from the equality terms of the filter is
   * inserted, updated, and reported in `upsertedId` when nothing matches.
   *
   * @returns `modifiedCount` counts only documents whose stored bytes
   *   actually changed.
   */
  public async updateOne(
    filter: Filter<TDocument>,
    update: UpdateFilter<TDocument>,
    options: UpdateOptions = {},
  ): Promise<UpdateResult> {
    return this.runUpdate("updateOne", filter, update, options);
  }

  /**
   * Applies an update to every matching document.
   *
   * With `upsert`, a document seeded from the equality terms of the filter is
   * inserted, updated, and reported in `upsertedId` when nothing matches.
   *
   * @returns `modifiedCount` counts only documents whose stored bytes
   *   actually changed.
   */
  public async updateMany(
    filter: Filter<TDocument>,
    update: UpdateFilter<TDocument>,
    options: UpdateOptions = {},
  ): Promise<UpdateResult> {
    return this.runUpdate("updateMany", filter, update, options);
  }

  /**
   * Creates an index, or confirms that an identical one exists. The collection
   * is created if it does not exist. A unique index fails with a
   * `DuplicateKey` server error when existing documents already violate it.
   */
  public async createIndex(
    definition: IndexDefinition<TDocument>,
  ): Promise<CreateIndexResult> {
    const value = await this.database.client.executeCommand(
      this.database.name,
      "createIndex",
      {
        collection: this.name,
        index: { ...definition } as unknown as Document,
      },
    );

    return parseCreateIndexResult(value);
  }

  /** Drops an index by name. The `_id` index cannot be dropped. */
  public async dropIndex(name: string): Promise<void> {
    await this.database.client.executeCommand(this.database.name, "dropIndex", {
      collection: this.name,
      name,
    });
  }

  /** The `_id` index first, then the others in creation order. */
  public async indexes(): Promise<IndexInfo[]> {
    const value = await this.database.client.executeCommand(
      this.database.name,
      "listIndexes",
      { collection: this.name },
    );

    return parseIndexList(value);
  }

  /** Asks the server to rebuild every index and report any difference. */
  public async validateIndexes(): Promise<IndexValidationResult> {
    const value = await this.database.client.executeCommand(
      this.database.name,
      "validateIndexes",
      { collection: this.name },
    );

    return parseIndexValidation(value);
  }

  /**
   * Starts a query and returns a cursor. No request is sent until the cursor
   * is read.
   *
   * The cursor can be read with `next()`, collected with `toArray()`, or
   * iterated with `for await`. Always finish or `close()` it so the server
   * can release it.
   */
  public find(
    filter: Filter<TDocument> = {} as Filter<TDocument>,
    options: FindOptions<TDocument> = {},
  ): FindCursor<TDocument> {
    return new FindCursor<TDocument>(
      (command, parameters) =>
        this.database.client.executeCommand(
          this.database.name,
          command,
          parameters,
        ),
      this.name,
      filter as unknown as Document,
      options.batchSize,
      {
        ...(options.sort === undefined ? {} : { sort: options.sort }),
        ...(options.skip === undefined ? {} : { skip: options.skip }),
        ...(options.limit === undefined ? {} : { limit: options.limit }),
      },
    );
  }

  private async runDelete(
    command: "deleteOne" | "deleteMany",
    filter: Filter<TDocument>,
  ): Promise<DeleteResult> {
    const value = await this.database.client.executeCommand(
      this.database.name,
      command,
      {
        collection: this.name,
        filter: filter as unknown as Document,
      },
    );

    return parseDeleteResult(value, command);
  }

  private async runUpdate(
    command: "updateOne" | "updateMany",
    filter: Filter<TDocument>,
    update: UpdateFilter<TDocument>,
    options: UpdateOptions,
  ): Promise<UpdateResult> {
    const value = await this.database.client.executeCommand(
      this.database.name,
      command,
      {
        collection: this.name,
        filter: filter as unknown as Document,
        update: update as unknown as Document,
        ...(options.upsert === undefined ? {} : { upsert: options.upsert }),
      },
    );

    return parseUpdateResult(value, command);
  }
}

function parseInsertOneResult(value: DocumentValue): InsertOneResult {
  if (!isPlainDocument(value)) {
    throw invalidInsertResult();
  }

  const acknowledged = value["acknowledged"];
  const insertedId = value["insertedId"];

  if (acknowledged !== true || !(insertedId instanceof CustomId)) {
    throw invalidInsertResult();
  }

  return Object.freeze({
    acknowledged: true,
    insertedId,
  });
}

function parseInsertManyResult(value: DocumentValue): InsertManyResult {
  if (!isPlainDocument(value)) {
    throw invalidInsertManyResult();
  }

  const acknowledged = value["acknowledged"];
  const insertedCount = value["insertedCount"];
  const insertedIds = value["insertedIds"];

  if (
    acknowledged !== true ||
    typeof insertedCount !== "number" ||
    !Number.isSafeInteger(insertedCount) ||
    insertedCount < 0 ||
    !Array.isArray(insertedIds) ||
    !insertedIds.every(
      (insertedId): insertedId is CustomId => insertedId instanceof CustomId,
    ) ||
    insertedIds.length !== insertedCount
  ) {
    throw invalidInsertManyResult();
  }

  return Object.freeze({
    acknowledged: true,
    insertedCount,
    insertedIds: Object.freeze([...insertedIds]),
  });
}

function parseFindOneResult<TDocument extends object>(
  value: DocumentValue,
): WithId<TDocument> | null {
  if (!isPlainDocument(value) || !Object.hasOwn(value, "document")) {
    throw invalidFindResult();
  }

  const document = value["document"];

  if (document === null) {
    return null;
  }

  if (!isPlainDocument(document) || !(document["_id"] instanceof CustomId)) {
    throw invalidFindResult();
  }

  return document as unknown as WithId<TDocument>;
}

function parseUpdateResult(
  value: DocumentValue,
  command: string,
): UpdateResult {
  if (!isPlainDocument(value)) {
    throw invalidWriteResult(command);
  }

  const matchedCount = value["matchedCount"];
  const modifiedCount = value["modifiedCount"];
  const upsertedId = value["upsertedId"];

  if (
    value["acknowledged"] !== true ||
    !isCount(matchedCount) ||
    !isCount(modifiedCount) ||
    modifiedCount > matchedCount ||
    !(upsertedId === null || upsertedId instanceof CustomId)
  ) {
    throw invalidWriteResult(command);
  }

  return Object.freeze({
    acknowledged: true,
    matchedCount,
    modifiedCount,
    upsertedId,
  });
}

function parseDeleteResult(
  value: DocumentValue,
  command: string,
): DeleteResult {
  if (!isPlainDocument(value)) {
    throw invalidWriteResult(command);
  }

  const deletedCount = value["deletedCount"];

  if (value["acknowledged"] !== true || !isCount(deletedCount)) {
    throw invalidWriteResult(command);
  }

  return Object.freeze({ acknowledged: true, deletedCount });
}

function isCount(value: unknown): value is number {
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
}

function isPlainDocument(value: unknown): value is Document {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return false;
  }

  const prototype = Object.getPrototypeOf(value);

  return prototype === Object.prototype || prototype === null;
}

function translateInsertManyFailure(error: unknown): never {
  if (!(error instanceof SinterServerError) || error.details === undefined) {
    throw error;
  }

  const failedIndex = error.details["failedIndex"];
  const insertedIds = error.details["insertedIds"];

  if (
    typeof failedIndex !== "number" ||
    !Number.isSafeInteger(failedIndex) ||
    failedIndex < 0 ||
    !Array.isArray(insertedIds) ||
    !insertedIds.every(
      (insertedId): insertedId is CustomId => insertedId instanceof CustomId,
    )
  ) {
    throw error;
  }

  throw new SinterInsertManyError(error, failedIndex, insertedIds);
}

function invalidInsertResult(): SinterProtocolError {
  return new SinterProtocolError(
    "The server returned an invalid insertOne result.",
  );
}

function invalidInsertManyResult(): SinterProtocolError {
  return new SinterProtocolError(
    "The server returned an invalid insertMany result.",
  );
}

function invalidFindResult(): SinterProtocolError {
  return new SinterProtocolError(
    "The server returned an invalid findOne result.",
  );
}

function invalidWriteResult(command: string): SinterProtocolError {
  return new SinterProtocolError(
    `The server returned an invalid ${command} result.`,
  );
}
