packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

allowBuilds:
  esbuild: true

catalog:
  "@types/node": "latest"
  "typescript": "latest"
  "vitest": "latest"
  "tsup": "latest"

minimumReleaseAgeExclude:
  - prettier@3.9.7
