import type { Metadata } from "next";

import { ApiReflectionPage } from "../../_components/pages";
import type { ApiPage } from "../../_generated/model";

const page = {
  "id": 272,
  "name": "OptionalId",
  "kind": "type-alias",
  "label": "Type Alias",
  "href": "/docs/api/types/OptionalId",
  "description": "A document as accepted for insertion: _id is optional, and the server generates one when it is missing.",
  "badges": [],
  "declaration": [
    [
      "type ",
      "kw"
    ],
    [
      "OptionalId",
      "name"
    ],
    [
      "<",
      "pn"
    ],
    [
      "TDocument",
      "tp"
    ],
    [
      " extends ",
      "kw"
    ],
    [
      "object",
      "prim"
    ],
    [
      "> = ",
      "pn"
    ],
    [
      "Omit",
      "ref"
    ],
    [
      "<",
      "pn"
    ],
    [
      "TDocument",
      "tp"
    ],
    [
      ", ",
      "pn"
    ],
    [
      "\"_id\"",
      "lit"
    ],
    [
      "> & { ",
      "pn"
    ],
    [
      "readonly ",
      "kw"
    ],
    [
      "_id",
      "prop",
      "/docs/api/types/OptionalId#_id"
    ],
    [
      "?: ",
      "pn"
    ],
    [
      "CustomId",
      "ref",
      "/docs/api/classes/CustomId"
    ],
    [
      " }",
      "pn"
    ]
  ],
  "comment": {
    "summary": "<p>A document as accepted for insertion: <code>_id</code> is optional, and the server\ngenerates one when it is missing.</p>",
    "short": "A document as accepted for insertion: <code>_id</code> is optional, and the server generates one when it is missing.",
    "deprecated": null,
    "modifiers": [],
    "blocks": []
  },
  "typeParameters": [
    {
      "name": "TDocument",
      "code": [
        [
          "TDocument",
          "tp"
        ],
        [
          " extends ",
          "kw"
        ],
        [
          "object",
          "prim"
        ]
      ],
      "comment": null
    }
  ],
  "hierarchy": null,
  "signatureSection": null,
  "signatures": [],
  "sections": [
    {
      "id": "type-declaration",
      "title": "Properties",
      "members": [
        {
          "id": 274,
          "name": "_id",
          "anchor": "_id",
          "kind": "property",
          "label": "Property",
          "badges": [],
          "code": [
            [
              "readonly ",
              "kw"
            ],
            [
              "_id",
              "name"
            ],
            [
              "?: ",
              "pn"
            ],
            [
              "CustomId",
              "ref",
              "/docs/api/classes/CustomId"
            ]
          ],
          "comment": {
            "summary": "<p>The document's <code>_id</code>; generated by the server when omitted.</p>",
            "short": "The document's <code>_id</code>; generated by the server when omitted.",
            "deprecated": null,
            "modifiers": [],
            "blocks": []
          },
          "signatures": [],
          "members": [],
          "relations": [],
          "sources": [
            {
              "path": "packages/driver/src/collection.ts",
              "line": 34,
              "url": "https://github.com/SinterDB/sinterdb/blob/ecd947da3fe7f4dae22317777a4896e9c5fee115/packages/driver/src/collection.ts#L34"
            }
          ]
        }
      ]
    }
  ],
  "toc": [
    {
      "id": "type-declaration",
      "title": "Properties",
      "items": [
        {
          "anchor": "_id",
          "name": "_id",
          "kind": "property"
        }
      ]
    }
  ],
  "sources": [
    {
      "path": "packages/driver/src/collection.ts",
      "line": 32,
      "url": "https://github.com/SinterDB/sinterdb/blob/ecd947da3fe7f4dae22317777a4896e9c5fee115/packages/driver/src/collection.ts#L32"
    }
  ]
} satisfies ApiPage;

export const metadata: Metadata = {
  title: page.name,
  description: page.description || undefined,
};

export default function Page() {
  return <ApiReflectionPage page={page} />;
}
